services:
  - type: web
    name: healthbridge
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: default
